APP: 
 TITLE: "catastrophic forgetting experience in GNN"
 VERSION: "1.0.0"

ENV: "development"

MODEL:
 BATCH_SIZE: 50
 TOTAL_EPOCHS: 200
 LEARNING_RATE: 3e-4
 DROPOUT: 0.2
 WEIGHT_DECAY: 5e-5
 IS_GAT: False
 N_HIST: 9
 N_PRED: 12

DIR:
 CHECKPOINT: "./checkpoints"
 LOG: "./logs"

DATA:
 PEMSD7:
  N_NODES: 228
  N_DAYS: 44
  N_INTERVALS: 288
  N_SLOTS: None