env: "developement"
app: 
 title: "catastrophic forgetting experience in GNN"
 version: "1.0.0"

model:
 BATCH_SIZE: 50
 N_EPOCHS: 200
 P_LR: 3e-4
 P_DROPOUT: 0.2
 P_WEIGHT_DECAY: 5e-5
 N_HIST: 9
 N_PRED: 12
 N_DAYS: 44
 N_INTERVALS: 288
 N_NODES: 228
 IS_GAT: True